// ESLint for the SvelteKit demo. Until now `web/` had no linter at all — `pnpm check` is
// svelte-check, which is types-only.
//
// This matters more than it looks: the repo's `.semgrep/` rules cover the Rust workspace and
// `web/src/lib/**/*.ts`, but **semgrep cannot parse `.svelte` at all** (it scans zero files), and
// `routes/+page.svelte` is where the editor is actually wired up. ESLint is the only thing that
// reads those files.
//
// Plugin set per the project lint baseline: sonarjs (bug patterns + duplication), unicorn (modern
// idiom), security (injection sinks).
import js from "@eslint/js";
import security from "eslint-plugin-security";
import sonarjs from "eslint-plugin-sonarjs";
import svelte from "eslint-plugin-svelte";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";
import ts from "typescript-eslint";
import svelteParser from "svelte-eslint-parser";

export default [
  {
    ignores: [
      "build/",
      ".svelte-kit/",
      "static/",
      "node_modules/",
      // wasm-pack output — generated glue, regenerated by `pnpm run wasm`.
      "../crates/rlt-wasm/pkg/",
      "src/lib/wasm/**",
    ],
  },

  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs["flat/recommended"],
  sonarjs.configs.recommended,
  security.configs.recommended,
  unicorn.configs["recommended"],

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // --- Project baseline: no `any`, narrow from `unknown` instead. ------------------------
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],

      // --- unicorn: keep the substance, drop the renaming/formatting campaigns. --------------
      // These five accounted for 213 of the 262 findings on the first run over an otherwise clean
      // tree — all of them "rename this" or "reformat this", none of them a defect. A linter that
      // reports 262 errors on working code is one nobody runs, which costs more than it buys.
      //
      // `err`, `req`, `res`, `buf`, `b2u`, `cfg` are this codebase's vocabulary and are defined in
      // the doc comments that introduce them.
      "unicorn/name-replacements": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/consistent-boolean-name": "off",
      // `//` comments are the house style across the Rust workspace and `web/` alike.
      "unicorn/single-line-block-comment-style": "off",
      "unicorn/switch-case-braces": "off",
      "unicorn/numeric-separators-style": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/consistent-class-member-order": "off",
      "unicorn/consistent-function-scoping": "off",
      // Module-scoped lazy-init singletons (`initPromise` in wasm.ts, `monacoPromise` in
      // monaco.ts, the worker's `store`/`manager`) are assigned once from inside the function that
      // creates them — that is the memoization pattern, not accidental global mutation. The rule
      // cannot tell the two apart.
      "unicorn/no-top-level-assignment-in-function": "off",
      // `.then()` in the artifact store is deliberate: the progressive-load path starts several
      // fetches and explicitly does NOT await them in sequence. Rewriting to `await` would
      // serialize the thing whose whole point is that it does not.
      "unicorn/prefer-await": "off",
      "unicorn/prefer-then-catch": "off",
      // UNSAFE AUTOFIX — leave off. Its fix rewrites
      // `new Worker(new URL("./checker.worker.ts", import.meta.url))` to drop the `./`, and that
      // prefix is exactly what makes Vite treat the specifier as a relative module to bundle as a
      // worker rather than a bare package id. Applying it builds a broken worker.
      "unicorn/relative-url-style": "off",
      // `window.matchMedia` in a Svelte component reads clearer than `globalThis.matchMedia`, and
      // the rule then flags its own fix with `no-unnecessary-global-this`.
      "unicorn/prefer-global-this": "off",
      // `Iterator#toArray()` is ES2025 — still missing from Safari and older evergreen builds, and
      // this is a public demo page with no polyfill. `[...map.values()]` works everywhere.
      "unicorn/prefer-iterator-to-array": "off",
      // `b2u`, `cfg`, `db` are this codebase's vocabulary; spanmap.ts's doc comments define
      // them. Renaming them to `byteToUtf16` everywhere would obscure, not clarify.
      "unicorn/prevent-abbreviations": "off",
      // The checker deals in null-vs-undefined at the wasm boundary, where `null` is what
      // serde-wasm-bindgen actually produces.
      "unicorn/no-null": "off",
      // Filenames here follow SvelteKit's conventions (`+page.svelte`, `+layout.ts`).
      "unicorn/filename-case": "off",
      // `reduce` is used deliberately in the artifact store's size accounting.
      "unicorn/no-array-reduce": "off",

      // --- security: this is a static, offline, client-side page. ---------------------------
      // Every "object injection" here is indexing a typed record with a known key; the rule is
      // ~100% false positives on TypeScript and has no taint analysis behind it.
      "security/detect-object-injection": "off",
    },
  },

  // Svelte components: parsed by svelte-eslint-parser, with <script lang="ts"> handed to the TS parser.
  {
    files: ["**/*.svelte"],
    languageOptions: {
      parser: svelteParser,
      parserOptions: { parser: ts.parser, extraFileExtensions: [".svelte"] },
    },
    rules: {
      // A top-level `let` in a component's <script> IS the component's reactive state, and
      // assigning to it from a handler is Svelte's entire programming model — the rule is written
      // for plain modules, where a top-level binding is module-global. 37 findings, all of them
      // ordinary Svelte.
      "unicorn/no-top-level-assignment-in-function": "off",
    },
  },

  // Test files and build scripts: console output is their reporting channel, they legitimately
  // shell out and exit with a status, and they read paths assembled from their own arguments.
  {
    files: ["**/*.test.ts", "scripts/**", "*.config.ts", "*.config.js"],
    rules: {
      "no-console": "off",
      "sonarjs/no-duplicate-string": "off",
      "unicorn/no-process-exit": "off",
      "sonarjs/no-os-command-from-path": "off",
      "security/detect-non-literal-fs-filename": "off",
    },
  },
];
